name: CI/CD Backend Deployment

on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Login to Amazon ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t backend-images:latest .
          docker tag backend-images:latest 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      # Deploy to EC2 #1
      - name: Deploy to EC2 #1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 3000:3000 --name backend --restart unless-stopped 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      # Deploy to EC2 #2
      - name: Deploy to EC2 #2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 3000:3000 --name backend --restart unless-stopped 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
            
