name: CI/CD Backend Deployment

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 949156002967
  ECR_REPOSITORY: backend-images
  IMAGE_TAG: latest

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::516035591988:role/demo
          aws-region: ap-south-1

      - name: Verify OIDC access
        run: aws sts get-caller-identity

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t backend-images:latest .
          docker tag backend-images:latest 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      - name: Push Docker image to ECR
        run: |
          docker push 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      - name: Deploy to EC2 #1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 949156002967.dkr.ecr.ap-south-1.amazonaws.com
            docker stop backend || true
            docker rm backend || true
            docker rmi backend-images:latest || true
            docker rmi 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest || true
            docker pull 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
            docker run -d -p 3000:3000 --name backend --restart unless-stopped 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest

      - name: Deploy to EC2 #2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 949156002967.dkr.ecr.ap-south-1.amazonaws.com
            docker stop backend || true
            docker rm backend || true
            docker rmi backend-images:latest || true
            docker rmi 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest || true
            docker pull 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
            docker run -d -p 3000:3000 --name backend --restart unless-stopped 949156002967.dkr.ecr.ap-south-1.amazonaws.com/backend-images:latest
